### ISSUE TITLE
Incorrect use of `mirrored_supervisor`

### ISSUE THREAD

**Issue by dumbbell** [aweber/pgsql-listen-exchange#10]
In `src/pgsql_listen_sup.erl`, the following code cannot work:
```erlang
stop() ->
    ok = mirrored_supervisor:terminate_child(?MODULE),
    ok = mirrored_supervisor:delete_child(?MODULE).
```
`mirrored_supervisor:terminate_child/1` and `mirrored_supervisor:delete_child/1` do not exist: they take 2 arguments.

**Comment by gmr** [comment]
Thanks!
