### ISSUE TITLE
Error: {plugin_built_with_incompatible_erlang,"epgsql"}

### ISSUE THREAD

**Issue by Rajdattpawar** [aweber/pgsql-listen-exchange#12]
As I am using RabbitMq V3.5.1. 
I tried to install rabbitmq-plugins pgsql_listen_exchange which shows me following error

The following plugins have been enabled:
 epgsql
 pgsql_listen_exchange

Applying plugin configuration to rabbit@rpawar01-VirtualBox... failed.
Error: {plugin_built_with_incompatible_erlang,"epgsql"}

For installing plugins I followed these steps: 
1. Downloaded the pgsql-listen-exchange-0.3.0-v3.5.x.zip file and extract it and I found two files  i.e.
   epgsql-3.1.0-rmq0.3.0-v3.5.x-git9f52f19.ez
   pgsql_listen_exchange-0.3.0-v3.5.x.ez

2) I Placed this file in rabbitmq plugins folder i.e.
  /usr/lib/rabbitmq/lib/rabbitmq_server-3.5.1/plugins

3) After that I have executed following command .

rabbitmq-plugins enable pgsql_listen_exchange

Which shows above error.

Please let me know if anyone has a solution for it.

**Comment by gmr** [comment]
What version of Erlang are you running? The plugins are built against 17.5.

**Comment by Rajdattpawar** [comment]
I am using RabbitMQ 3.2.4, with Erlang R16B03 (erts-5.10.4).
And this Erlang version comes by default when I installed RabbitMQ.

**Comment by Rajdattpawar** [comment]
Thanks, I have upgraded Erlang version and plug-in installed successfully.

One more thing How we use this from PostgreSQL side, Is any document related to this?

**Comment by gmr** [comment]
http://www.postgresql.org/docs/9.1/static/sql-notify.html

Your binding key in RabbitMQ should be the channel you're sending notifications to.

**Comment by Rajdattpawar** [comment]
Thanks, It's working fine. 
Is any way to pass multiple database names to x-dbname or we need to create a multiple exchange to multiple databases?

**Comment by gmr** [comment]
You need an exchange per PostgreSQL connection
