### ISSUE TITLE
Configuration Confusion

### ISSUE THREAD

**Issue by phillpafford** [aweber/pgsql-listen-exchange#4]
Not sure if this is an issue but I'm confused at to what actually needs to be configured for a connection.

Example:

Can I just configure the Policy or do I need to setup the exchange connection method as well?

Q: Do I need or Can I have more than one connection configured?

If yes, how and benefits?

**Comment by gmr** [comment]
Sorry for missing this, the exchange has to be created as an x-pgsql-listen exchange and be configured to connect. Configuration can be made as arguments or as a policy. Each binding maps to a notification channel in PostgreSQL and it is a direct exchange.
